### ISSUE TITLE
Sonarr updated itself and now importing doesn't work

### ISSUE THREAD

**Issue by PehrGit** [mafredri/asustor-sonarr#1]
Hi,

Sonarr recently updated itself, and now I get an error when importing that "[file] has a runtime of 0, is it a valid video file?" 

I posted the question on the Sonarr forums ([here](https://forums.sonarr.tv/t/file-has-a-runtime-of-0-is-it-a-valid-video-file-on-asustor-adm/10821)) and the problem may be an old version of mediainfo. Could you update the Sonarr ADM package to the latest version including the latest version of mediainfo?

Thanks so much for maintaining this package!

**Comment by mafredri** [comment]
Thanks for reporting, I'll try to have a look at it as soon as I have some free time!

Did you recently update to ADM `2.6.1` as well? I believe that could be the most likely culprit, I have not yet updated myself. Either way, there are newer versions of mediainfo so it's due for an update anyway :).

**Comment by PehrGit** [comment]
Thanks for the quick reply! Yes I did update ADM and now that you mention it, that may have been when Sonarr started to misbehave...

Is there anything I can do in the mean time? Manually update mediainfo via SSH for instance?

**Comment by mafredri** [comment]
We can try, which NAS model do you have?

**Comment by PehrGit** [comment]
Great! I have an AS1004T

**Comment by mafredri** [comment]
Alright, that's unfortunate as updating the ARM will take a little bit more time, I can't give you anything to test right away.

I'll have to update my toolchain to support ADM `2.6.1`. I'm working on it though and I'll keep you posted when I have something you can try out!

**Comment by PehrGit** [comment]
No worries, I'm using manual import as a workaround for now. Thanks for the effort!

**Comment by mafredri** [comment]
@PehrGit sorry for the long delay, would you mind testing this: [sonarr_2.0.0.4145.999_arm.apk](https://app.box.com/s/zs48g3rvio0i39qfi23gzrlpdn61pgqt)?

It seems Asustor changed their toolchain from softfp to hardfloat which was unexpected and a lot of time down the drain 😞 .

**Comment by PehrGit** [comment]
No worries at all, I'll test it today :smile:

**Comment by PehrGit** [comment]
It seems to work! After updating, the one file that was in the queue which I was planning to import manually was instantly processed. I also forced a search for some other episodes and all seems to be well :)

**Comment by mafredri** [comment]
Great, thanks for testing! :)
