### ISSUE TITLE
MediaInfo could not be loaded libmediainfo.so.0

### ISSUE THREAD

**Issue by hukoeth** [mafredri/asustor-sonarr#2]
Hi, Thanks for the great package. Unfortunately with the latest update, the error MediaInfo could not be loaded libmediainfo.so.0 is back on ARM (AS1004T, ADM v2.6.5.R9N1). I downgraded and all is working fine. Thank you for looking into this. Let me know if you need any further information.

**Comment by mafredri** [comment]
Looks like `libzen` is the culprit, for some reason it's gotten linked to a more recent gcc ABI than available (asks for `GLIBCXX_3.4.20` whereas only `GLIBCXX_3.4.19` is available on the ARM platform). I'll have a new build shortly.

**Comment by mafredri** [comment]
Should be fixed in [2.0.0.4326-r1](https://github.com/mafredri/asustor-sonarr/releases/tag/2.0.0.4326-r1), sorry for the trouble @hukoeth and thanks for reporting!

**Comment by hukoeth** [comment]
Wow that was fast. I confirm that the issue is fixed. Thanks for the update.
